using System.Globalization;
using System.Reflection;

namespace AngelscriptApiMcp;

/// <summary>
/// Server configuration from command-line arguments and environment variables.
/// Arguments win over environment variables.
/// </summary>
public sealed class ServerOptions
{
    public const string DumpDirEnv = "ANGELSCRIPT_DUMP_DIR";
    public const string GuideCacheDirEnv = "ANGELSCRIPT_GUIDE_CACHE_DIR";
    public const string GuideUrlEnv = "ANGELSCRIPT_GUIDE_URL";
    public const string GuideMaxAgeEnv = "ANGELSCRIPT_GUIDE_MAX_AGE_DAYS";
    public const string OfflineEnv = "ANGELSCRIPT_OFFLINE";
    public const string ScriptDirsEnv = "ANGELSCRIPT_SCRIPT_DIRS";

    private static readonly Uri DefaultGuideUrl = new("https://angelscript.hazelight.se/");
    private static readonly TimeSpan DefaultGuideMaxAge = TimeSpan.FromDays(7);

    /// <summary>
    /// Folder of <c>.hpp</c> files written by the editor's <c>-dump-as-doc</c> switch, or the project
    /// root that contains <c>Docs/angelscript/generated</c>.
    /// </summary>
    public string? DumpDir { get; init; }

    /// <summary>Folders searched recursively for the project's own <c>.as</c> files. Empty: scripts are not indexed.</summary>
    public IReadOnlyList<string> ScriptDirs { get; init; } = [];

    public string GuideCacheDir { get; init; } = DefaultGuideCacheDir;

    public Uri GuideBaseUrl { get; init; } = DefaultGuideUrl;

    public TimeSpan GuideMaxAge { get; init; } = DefaultGuideMaxAge;

    /// <summary>Never download the guide; use only what is already cached.</summary>
    public bool Offline { get; init; }

    public static string DefaultGuideCacheDir => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "angelscript-api-mcp", "guide");

    public static string Version { get; } = ReadVersion();

    public static string Usage => $"""
        angelscript-api-mcp {Version} - MCP server (stdio) for the Unreal Engine Angelscript API and guide.

        Usage: angelscript-api-mcp --dump-dir <path> [--script-dir <path>]... [options]

          --dump-dir <path>            Output of the editor's -dump-as-doc switch
                                       (<Project>/Docs/angelscript/generated), or the project root.  [{DumpDirEnv}]
          --script-dir <path>          A folder of the project's own .as files, searched recursively
                                       and kept current as files change. Repeatable.                  [{ScriptDirsEnv}, '{Path.PathSeparator}'-separated]
          --guide-cache-dir <path>     Where the downloaded guide is cached.                          [{GuideCacheDirEnv}]
                                       Default: {DefaultGuideCacheDir}
          --guide-url <url>            Guide site to read. Default: {DefaultGuideUrl}             [{GuideUrlEnv}]
          --guide-max-age-days <days>  Re-download the guide after this many days. Default: 7         [{GuideMaxAgeEnv}]
          --offline                    Never download; use the cached guide only.                     [{OfflineEnv}=1]
          --help                       Show this help.
        """;

    public string Instructions => $"""
        Reference for Unreal Engine Angelscript (the Hazelight UnrealEngine-Angelscript fork).

        - API tools (search_api, get_type, get_member) read the documentation dump generated by the user's own engine with -dump-as-doc, so type names, signatures and inheritance match the engine version actually in use. Check them before writing Angelscript that calls engine or C++-bound APIs instead of relying on memory: script bindings differ from the C++ and Blueprint names (for example, static library functions live in namespaces such as System:: and Math::).
        - {(ScriptDirs.Count > 0
            ? "The project's own .as files are indexed as well and re-checked on every call: script classes, structs, enums, delegates, functions and properties appear in the same tools with their file and line, linked into the engine inheritance tree. list_script_types lists them, optionally only those deriving from a base class; search_api with origin=script restricts a search to them."
            : "The dump covers C++ types bound to script, not classes declared in the project's own .as files; read those scripts directly.")}
        - Guide tools (search_guide, read_guide_page, list_guide_pages) read the language manual at angelscript.hazelight.se: script syntax, UCLASS/UPROPERTY/UFUNCTION specifiers, default components, delegates, mixins, format strings, networking, subsystems and script tests.
        - The status tool reports where each data source comes from and whether it loaded.
        """;

    public static ServerOptions Parse(IReadOnlyList<string> args, Func<string, string?>? environment = null)
    {
        environment ??= Environment.GetEnvironmentVariable;

        string? dumpDir = NullIfEmpty(environment(DumpDirEnv));
        string? cacheDir = NullIfEmpty(environment(GuideCacheDirEnv));
        string? guideUrl = NullIfEmpty(environment(GuideUrlEnv));
        string? maxAgeDays = NullIfEmpty(environment(GuideMaxAgeEnv));
        bool offline = IsTruthy(environment(OfflineEnv));
        List<string> environmentScriptDirs = (environment(ScriptDirsEnv) ?? "")
            .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .ToList();
        var argumentScriptDirs = new List<string>();

        for (int i = 0; i < args.Count; i++)
        {
            switch (args[i])
            {
                case "--dump-dir":
                    dumpDir = ValueAfter(args, ref i);
                    break;
                case "--script-dir":
                    argumentScriptDirs.Add(ValueAfter(args, ref i));
                    break;
                case "--guide-cache-dir":
                    cacheDir = ValueAfter(args, ref i);
                    break;
                case "--guide-url":
                    guideUrl = ValueAfter(args, ref i);
                    break;
                case "--guide-max-age-days":
                    maxAgeDays = ValueAfter(args, ref i);
                    break;
                case "--offline":
                    offline = true;
                    break;
                default:
                    throw new ArgumentException($"Unknown argument '{args[i]}'.");
            }
        }

        return new ServerOptions
        {
            DumpDir = dumpDir,
            ScriptDirs = argumentScriptDirs.Count > 0 ? argumentScriptDirs : environmentScriptDirs,
            GuideCacheDir = cacheDir ?? DefaultGuideCacheDir,
            GuideBaseUrl = guideUrl is null ? DefaultGuideUrl : ParseBaseUrl(guideUrl),
            GuideMaxAge = maxAgeDays is null ? DefaultGuideMaxAge : TimeSpan.FromDays(ParseDays(maxAgeDays)),
            Offline = offline,
        };
    }

    private static string ValueAfter(IReadOnlyList<string> args, ref int i)
    {
        if (i + 1 >= args.Count || args[i + 1].StartsWith("--", StringComparison.Ordinal))
            throw new ArgumentException($"Argument '{args[i]}' needs a value.");
        return args[++i];
    }

    private static Uri ParseBaseUrl(string value)
    {
        if (!Uri.TryCreate(value, UriKind.Absolute, out Uri? url) || (url.Scheme != Uri.UriSchemeHttp && url.Scheme != Uri.UriSchemeHttps))
            throw new ArgumentException($"Guide URL '{value}' is not an absolute http(s) URL.");

        // Relative page paths resolve against the last '/', so the base must end with one.
        return url.AbsoluteUri.EndsWith('/') ? url : new Uri(url.AbsoluteUri + "/");
    }

    private static double ParseDays(string value)
    {
        if (!double.TryParse(value, NumberStyles.Float, CultureInfo.InvariantCulture, out double days) || days < 0)
            throw new ArgumentException($"Guide max age '{value}' is not a non-negative number of days.");
        return days;
    }

    private static string? NullIfEmpty(string? value) => string.IsNullOrWhiteSpace(value) ? null : value;

    private static bool IsTruthy(string? value) => value?.Trim().ToLowerInvariant() is "1" or "true" or "yes" or "on";

    private static string ReadVersion()
    {
        string? version = typeof(ServerOptions).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>()?.InformationalVersion;
        if (string.IsNullOrEmpty(version))
            return "0.0.0";

        // The SDK appends "+<commit>" when building from a git checkout.
        int metadata = version.IndexOf('+');
        return metadata >= 0 ? version[..metadata] : version;
    }
}
